version: "3.4"
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch --master-key=masterKey --no-analytics=true
    ports:
      - "7700:7700"
networks:
  default:
