name: Deploy archived notes to branch

on:
  schedule:
    - cron: "0 17 * * *"
  push:
    branches:
      - main


jobs:
  deploy-dev-pycontw-sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install
      - name: Crawl Past PyConTW Websites
        run: |
          pipenv run python3 app/main.py sync-all-hackmd-notes
        env:
          HACKMD_COOKIE: ${{ secrets.HACKMD_COOKIE }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          clean: false
